language: node_js
services:
- docker
node_js:
- '10.7'
before_script:
- yarn build-prod
- yarn build-prod-docker
script:
- bash scripts/test-docker.sh
after_success:
- docker login -u="ashwinath" -p="$DOCKER_PASSWORD"
- if [[ $TRAVIS_BRANCH = master ]]; then docker push ashwinath/personal-website-3:latest;
  else true; fi
- if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then docker push ashwinath/personal-website-3:$TRAVIS_TAG;
  else true ; fi
- bash scripts/deploy.sh
env:
  global:
    secure: zHiuXuazy+LIfqsmZOGz3229BxKFdL5p1T9c8psmIDbROUvwd1hrENbZyK/fwlzkT4czCKKnmGpN8t6Jjxi8O+NS8/rHiLYNjmkjREby0C5Ec3yNhiG3AMfRYxdQwMxRMNFmXVZWcmg3GmRlmyE+ouRmz/2113+/ormbzXqGXm02ixy3IQ4r80+PUtjS2LsoXv/b2KtOTwNYwcO59tmzXZmV17+29Zf9oH6C4jMEdgX30um+P3xyrE9UKhdlivpwdPjHh38MPmZPYacK8wzqDyPuiJsA7m14PdH3G0K25IOHsXRK7DyDQ7CFQm0w3+TmEaK9XLz5L6GTGky4N4op/Wk3Im/lCXqzwm8yaby0bMznBssq74f1T7j6Q5zeFPoqgt43ZAumXNBsBoSgwCGbnG0SEcfcVoG8QyUvTvTA/O9nEaTU78Sh+4FgGFblX3aENtD553XraGjT4cAF5nyWfUrrrGU9w/4NlzEs4jsVANsPAj4Eg8TRaTxxsYv978KDgQLL8jLQ1a9sYHE4jKfRQDbJ3C35Hv0JlMOIk2C32hxQLcrDB730hdepOQouZjxEtpLCosufPfsExba5AbCPVUoB+wTzyKOD6+Lgw6+dVrGROML/iIJyqseqd5AJQnqeRsU+53UEbVEo4yrPt0Z9hjSQp5zMXlQkP5llqEQvrpc=
before_install:
- openssl aes-256-cbc -K $encrypted_37f5e426fa3d_key -iv $encrypted_37f5e426fa3d_iv
  -in travis_rsa.enc -out ~\/.ssh/travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~\/.ssh/travis_rsa
- ssh-add ~\/.ssh/travis_rsa
